# DISTRIBUTION STATEMENT A. Approved for public release. Distribution is unlimited.
# This material is based upon work supported by the Dept of the Navy under Air
# Force Contract No. FA8702-15-D-0001 or FA8702-25-D-B002.
# Any opinions, findings, conclusions or recommendations expressed in this material
# are those of the author(s) and do not necessarily reflect the views of the Dept
# of the Navy.
# (c) 2024 Massachusetts Institute of Technology.
# The software/firmware is provided to you on an As-Is basis.
# Delivered to the U.S. Government with Unlimited Rights, as defined in DFARS Part
# 252.227-7013 or 7014 (Feb 2014).
# Notwithstanding any copyright notice, U.S. Government rights in this work are
# defined by DFARS 252.227-7013 or DFARS 252.227-7014 as detailed above.
# Use of this work other than as specifically authorized by the U.S. Government may
# violate any copyrights that exist in this work.
name: Publish Plugin

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest

    outputs:
      v-version: ${{ steps.version.outputs.v-version }}

    steps:
      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          release_branch: master
          use_api: true

  build_plugin:
    needs: create_release
    runs-on: ubuntu-22.04

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create the JAR file for upload

      - name: Upload debian package to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            ./plugin.xml
            ./*.jar
